Loop
jihard/Cshaarp-taining pull request #10
Opened 2021-07-28 06:47 UTC by jihard

2021-07-28 18:54 UTC, ausmoons commented on LoopExercise1/Program.cs
> +            int i;
Tev kkas nav ok ar spaciem

2021-07-28 18:55 UTC, ausmoons commented on LoopExercise2/Program.cs
> +          if (n == 0)
Sakārto visos failos spacingu/tabingu

2021-07-28 18:56 UTC, ausmoons commented on LoopExercise5/Program.cs
> +		if (counting <= 30) periods = 30 - counting;
Trūkst {}

2021-07-28 18:58 UTC, ausmoons requested changes
Sakārto visur tabingu, spacingu, {} un tukšās rindas

2021-07-29 16:44 UTC, ausmoons requested changes

2021-07-29 16:44 UTC, ausmoons commented on LoopExercise5/Program.cs
> +		{
Te vēl joprojām ir par daudz tab no malas. Un labojumus visus taisi vienā commitā

2021-07-29 16:45 UTC, ausmoons commented on LoopExercise5/Program.cs
> +		{
Arīcitos failos nav sakārti spacingi

2021-07-29 17:35 UTC, ausmoons commented on LoopExercise1/Program.cs
> +            Console.Write("{0} ", i);
Trūkst viena taba

2021-07-29 17:47 UTC, ausmoons requested changes
Izej cauri katram failam un sakārto visu.

2021-07-29 17:47 UTC, ausmoons commented on LoopExercise10/Program.cs
> +          Console.Write("Enter Min? ");
Visur sakārto spacingus/tabingus

2021-07-29 17:47 UTC, ausmoons commented on LoopExercise2/Program.cs
> +         else if (n % 2 == 0)
Šeit viaur saliec {}, te neko nevar saprast

2021-07-29 18:53 UTC, jihard commented on LoopExercise5/Program.cs
> +		{
![Capture1](https://user-images.githubusercontent.com/83280524/127549173-08b24c08-6658-45c9-b3fb-67e35cf710da.JPG)
Šeit ir salīdzinājums kā  5. uzdevuma  fails izskatās Visual studio pirms publicēšanas githubā, un kāds izskatās pēc publicēšanas. Tur noteikti ir kāda tehniska kļūdas, kādēļ github attēlo kodu šādi.

2021-07-31 07:00 UTC, ausmoons requested changes

2021-08-01 11:32 UTC, closed without merging