Arithmetic
jihard/Cshaarp-taining pull request #6
Opened 2021-07-18 23:07 UTC by jihard

2021-07-18 23:15 UTC, jihard commented
Aritmetic

2021-07-19 18:49 UTC, ausmoons commented on Arithmetics/ArithmeticEX/Program.cs
> +            Console.WriteLine("Arithmetic");
Kas ir šis?

Kāpēc aiztikts gitignore? Ir Bin faili

2021-07-19 18:50 UTC, ausmoons commented on Arithmetics/ArithmeticExercise1/Program.cs
> +            bool test = x == 15 || y == 15 || x + y == 15;
Kur starpība?

2021-07-19 18:51 UTC, ausmoons commented on Arithmetics/ArithmeticExercise10/Geometry.cs
> +            return area = 2 * PI * radius;
Liekas tukšas rindas. Ja return, tad nav jādeklarē un noteikti nav jāpārdod area

2021-07-19 18:52 UTC, ausmoons commented on Arithmetics/ArithmeticExercise10/Geometry.cs
> +            throw new NotImplementedException();
Já kkas nav padots, tad throw an exception. Šādies neko nevar saprast

2021-07-19 18:58 UTC, ausmoons requested changes

2021-07-19 18:58 UTC, ausmoons commented on Arithmetics/ArithmeticExercise2/Program.cs
> +            }
Pēc trūkst tukšas rindas, bet pirms tam atstāji liekas rindas

2021-07-19 18:58 UTC, ausmoons commented on Arithmetics/ArithmeticExercise5/Program.cs
> +                if (guess > num)
Else if un pēc tam else

2021-07-19 18:58 UTC, ausmoons commented on Arithmetics/ArithmeticExercise6/Program.cs
> +            for (int i = 1; i < 111; i++)
I =0,110

2021-07-19 18:58 UTC, ausmoons commented on Arithmetics/ArithmeticExercise8/Program.cs
> +        double emp_sal;
Nākotnē neizmantot šādus saīsinājumus

2021-07-19 18:58 UTC, ausmoons commented on Arithmetics/ArithmeticExercise8/Program.cs
> +            if (hr > 60)
Else if, else

2021-07-19 18:58 UTC, ausmoons commented on Arithmetics/ArithmeticExercise8/Program.cs
> +        public void display()
Metodes sākas ar lielo burtu

2021-07-19 18:58 UTC, ausmoons commented on Arithmetics/ArithmeticExercise8/Program.cs
> +            emp k = new emp();
E? K?

2021-07-19 18:58 UTC, ausmoons commented on Arithmetics/ArithmeticExercise9/Program.cs
> +            double Bmi;
Ar mazo burtu bmi

2021-07-19 18:58 UTC, ausmoons commented on Arithmetics/ArithmeticExercise9/Program.cs
> +                    Console.WriteLine("person is considered Overweight");
Else

2021-07-19 18:58 UTC, ausmoons commented on Arithmetics/ArithmeticExercise9/Program.cs
> +                return;
Tev ir void, neko nevajag returnot

2021-07-22 08:20 UTC, closed without merging